baseurl = "//luizdepra.com/"
title = "luizdepra"

theme = "coder"

languagecode = "en"

canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleanalytics = "UA-68141818-1"

[permalinks]
    post = "post/:title/"
    default = ":title/"

[params]
    author = "Luiz de Prá"
    info = "Software and Game Developer"
    description = "Luiz de Prá's personal website and blog"
    keywords = "blog,developer,personal,python,c++,go,rust"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/luizdepra/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/luizdepra/"
[[params.social]]
    name = "RSS"
    weight = 3
    url = "/index.xml"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
