title = "luizdepra"

theme = "coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[params]
    author = "Luiz de Prá"
    description = "Luiz de Prá's personal website and blog"
    keywords = "blog,developer,personal,python,c++,go,rust"
    info = "Software Engineer and Game Developer"
    avatarURL = "images/avatar.jpg"

    dateFormat = "2006-01-02"

    colorScheme = "dark"
    hideColorSchemeToggle = true

    customCSS = ["css/custom.css", "css/syntax.css"]

[params.goatCounter]
    code = "luizdepra"

[params.utteranc]
    repo = "luizdepra/luizdepra.com"
    issueTerm = "pathname"
    theme = "github-dark"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/luizdepra/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 2
    url = "https://twitter.com/luizdepra/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/luizdepra/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss-square"
    weight = 4
    url = "/index.xml"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "about/"
