baseurl = "//luizdepra.com/"
title = "luizdepra"
author = "Luiz F. A. de Prá"

theme = "black-and-light"

languagecode = "en"

canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusshortname = "luizdepracom"
googleanalytics = "UA-68141818-1"

[permalinks]
    post = "post/:title/"
    default = ":title/"

[params]
    sitename = "luizdepra"

[[menu.main]]
    name = "Blog"
    weight = -30
    url  = "/"
[[menu.main]]
    name = "Github"
    weight = -20
    url  = "https://github.com/luizdepra"
[[menu.main]]
    name = "About"
    weight = -10
    url = "/about/"
