[build]
    publish = "public"
    command = "hugo --gc --minify --baseURL $URL"

[context.production.environment]
    HUGO_VERSION = "0.55.4"

[[redirects]]
  from = "https://luizdepra.com/*"
  to = "https://luizdepra.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.luizdepra.com/*"
  to = "https://luizdepra.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://luizdepra.com.br/*"
  to = "https://luizdepra.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.luizdepra.com.br/*"
  to = "https://luizdepra.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://luizdepra-website.netlify.com/*"
  to = "https://luizdepra.dev/:splat"
  status = 301
  force = true
